connections:
  source:
    name: RedisConnect #database name
    db: RedisConnect #database
    hostname: redis-connect.demo.redislabs.com
    port: 1433
    username: sa
    password: Redis@123
    type: mssqlserver #this value can not be changed for mssqlserver
    jdbcUrl: "jdbc:sqlserver://redis-connect.demo.redislabs.com:1433;database=RedisConnect"
    maximumPoolSize: 20
    minimumIdle: 2
    tableName: dbo.emp
    pkey: empno
    batchSize: 500
    loadQueryFile: insert.sql
    csvFile: emp.csv
    select: select.sql
    updatedSelect: updatedSelect.sql
    update: update.sql
    delete: delete.sql
    sourceJsonFile: emp-source.json
    #loadQuery: "select * from dbo.emp"
    iteration: 1
  target:
    redisUrl: redis://redis-connect.demo.redislabs.com:14000
    keys: redis.keys
