connections:
  source:
    name: RedisConnect #database name
    db: RedisConnect #database
    hostname: 127.0.0.1
    port: 1433
    username: sa
    password: Redis@123
    type: mssqlserver #this value can not be changed for mssqlserver
    jdbcUrl: "jdbc:sqlserver://127.0.0.1:1433;database=RedisConnect"
    maximumPoolSize: 20
    minimumIdle: 2
    tableName: dbo.emp
    pkey: empno
    batchSize: 500
    loadQueryFile: insert.sql
    csvFile: emp.csv
    select: select.sql
    updatedSelect: updatedSelect.sql
    update: update.sql
    delete: delete.sql
    sourceJsonFile: emp-source.json
    #loadQuery: "select * from dbo.emp"
    iteration: 1
  target:
    redisUrl: redis://127.0.0.1:14000
    keys: redis.keys
    sourceFile: redis-connect-raw-events.out
    targetFile: redis-14000-07-12-2021.log
