connections:
  source:
    name: RedisLabsCDC #database name
    db: RedisLabsCDC #database
    hostname: localhost
    port: 1433
    username: sa
    password: Redis@123
    type: mssqlserver #this value can not be changed for mssqlserver
    maximumPoolSize: 20
    minimumIdle: 2
    tableName: dbo.emp
    pkey: empno
    batchSize: 500
    loadQueryFile: insert.sql
    csvFile: emp.csv
    select: select.sql
    updatedSelect: updatedSelect.sql
    update: update.sql
    delete: delete.sql
    sourceJsonFile: emp-source.json
    #loadQuery: "select * from dbo.emp"
    iteration: 20
  target:
    redisUrl: redis://35.185.69.89:14000
    keys: redis.keys
